<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RootNamespace>_180Detection</RootNamespace>
    <AssemblyName>180Detection</AssemblyName>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Properties\Settings.Designer.cs" />
    <Compile Remove="service\InferenceService.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="runtime\IndustrialAnomaly.Runtime\IndustrialAnomaly.Runtime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="config\appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
